### ISSUE TITLE
Main navigation not showing on mobile devices (responsive)

### ISSUE THREAD

**Issue by netlander** [marcoscv-work/madrid-theme#1] opened 2015-07-04 10:31 UTC
Hi Marco,

I've been looking at your themes recently because I need to create custom looks for some websites. Both Madrid and Manzanina look great.

In the Madrid theme I noticed that The main (top) navigation doen't show when the theme is viewed on a mobile device. Is this a feature or is there a setting I need to know about?

Many thanks
Netlander

**Comment by marcoscv-work** [comment] 2015-07-22 02:18
I'm not sure about If I'm understanding the problem, you should see a hamburger icon which provide a way to open the menu.

![image](https://cloud.githubusercontent.com/assets/7963804/8816572/287ae47e-3029-11e5-8b14-041f894f8af1.png)

Could you add a screenshot which showing the problem?

**Comment by patsoftware** [comment] 2015-08-11 14:07
I have the same problem.  
The problem occur when we build the plugins fromthe source. If we install the Theme from the marketplace the problem doesn't occur. 

The problem occur in css directive .aui #navigation{ display:none}

![mobile_navigation_problem](https://cloud.githubusercontent.com/assets/1749837/9199441/a14b64fe-4042-11e5-896b-f51161560928.jpg)

Cau you give us some directive to find the bug ?

**Comment by marcoscv-work** [comment] 2015-08-11 15:47
Hi,

Is this happening in tablet version?

thanks

2015-08-11 16:07 GMT+02:00 patsoftware notifications@github.com:

**Comment by patsoftware** [comment] 2015-08-11 16:04
Hi Marcos, 

you can reproduce it when you resize the browser. You can resize the browser like tablet size or mobile size. You will see that hamburger menù don't come showed 

Best regards,

**Comment by marcoscv-work** [comment] 2015-08-11 16:15
Are you sure?

I'm testing in different browsers and I haven't found out any problem:

[image: Imágenes integradas 1]

2015-08-11 18:04 GMT+02:00 patsoftware <notifications@github.com>:

**Comment by patsoftware** [comment] 2015-08-11 16:34
I'm sure, 

i have tested with Firefox and Chrome and in both i have the same problem. 

Have you tried to install the plugins from source code ? If you install plugin from marketPlace the problem doesn't occur. 

Best regards 

Antonio Patarozzi 

Pat Software 
Dyensì Software 
Antonio Patarozzi 

SS Consolare Rn-Rsm Nr. 13/15 
47900 Rimini (RN) 
Tel. (+39) 0541 1796012 
Fax. (+39) 0541 1791843 
website: http://www.patsoftware.it 
website: http://www.dyensisoftware.it 

LinkedIn : https://www.linkedin.com/pub/antonio-pat-patarozzi/5/26b/a21?domainCountryName=&csrfToken=ajax%3A2071018053878965951 
Twitter : https://twitter.com/PatSoftware

**Comment by patsoftware** [comment] 2015-08-11 17:04
In attachments i send you the result if i reinstall the madrid-Theme from marketPlace.

From marketPlace it's all ok but if you install from source code without any change the problem come back

Best regards 

Antonio Patarozzi 

Pat Software 
Dyensì Software 
Antonio Patarozzi 

SS Consolare Rn-Rsm Nr. 13/15 
47900 Rimini (RN) 
Tel. (+39) 0541 1796012 
Fax. (+39) 0541 1791843 
website: http://www.patsoftware.it 
website: http://www.dyensisoftware.it 

LinkedIn : https://www.linkedin.com/pub/antonio-pat-patarozzi/5/26b/a21?domainCountryName=&csrfToken=ajax%3A2071018053878965951 
Twitter : https://twitter.com/PatSoftware

**Comment by patsoftware** [comment] 2015-08-11 19:24
Below two attachments that describe result before and after build. Before is packed installed from marketPlace, The second is after build.
![mobile_navigation_problem_2](https://cloud.githubusercontent.com/assets/1749837/9207675/408a5026-406f-11e5-80d0-ff4c986932fd.jpg)
![mobile_navigation_problem](https://cloud.githubusercontent.com/assets/1749837/9207679/494729d2-406f-11e5-9020-86744f4e32a4.jpg)

Have you any suggestions ?

Best regards

Antonio Patarozzi

**Comment by marcoscv-work** [comment] 2015-08-12 08:06
Hi,

I've tested compiling the theme from plugins SDK and install from
Marketplace in Liferay GA1, GA3, GA4 and EE. and all is working fine for me.

Could you try to find out from where is coming this class: .aui
#navigation{ display:none}
because I don't have it. maybe It`s a content class, portlet or other
residual class.

If you still having doubts, you always could put:

#navigation {
     display: block !important
}

in theme settings -> custom CSS

2015-08-11 21:24 GMT+02:00 patsoftware <notifications@github.com>:

**Comment by patsoftware** [comment] 2015-08-12 10:47
Hi Marcos, 

the class .aui #navigation{ display:none} come from main.css.-> dockbar.css 

In dockbar.css at row 435: 

@media (max-width: 979px) { 
.aui #navigation { 
display: none; } 
.aui #navigation.open { 
display: block; } 
.aui .dockbar-split .dockbar { 
height: auto; 
position: relative; } 
.aui .dockbar-split .dockbar .navbar-inner { 
width: auto; } 
.aui .user-avatar-image { 
width: 18px; } } 

We use Liferay GA4 and we haven't did any change to GA4 or to plugins Madrid Theme. 

Can be we have different dockbar.css ? 

Best regards 

Antonio Patarozzi

**Comment by patsoftware** [comment] 2015-08-12 11:43
I have did other research and i have found that class .aui #navigation come from 
ROOT\html\themes\classic\css\.sass-cache\dockbar.css and 
ROOT\html\themes\control_panel\css\.sass-cache\dockbar.css 

best regards, 

Antonio Patarozzi

**Comment by marcoscv-work** [comment] 2015-08-12 12:04
You are finding these styles in:
classic theme, and control_panel theme.

It doesn't exist in my theme (based on _styled theme). So, I can't
understand why it is loading classic or control panel styles in
Madrid-theme.

Here you can see how madrid theme is based on _styled, not classic or
control_panel.
https://github.com/marcoscv-work/madrid-theme/blob/master/build.xml


2015-08-12 13:43 GMT+02:00 patsoftware <notifications@github.com>:

**Comment by patsoftware** [comment] 2015-08-12 12:10
Hi Marcos, 

I have found when the problem occurs. 
When you are logged in.If you are not logged the problems doesn't occurs and The navigaionbar is visible. 

Have you tried to rebuild from sourcecode get from github ? 

Best Regards 

Antonio Patarozzi

**Comment by marcoscv-work** [comment] 2015-08-12 12:21
I think you are using a wrong plugins-sdk.

2015-08-12 14:10 GMT+02:00 patsoftware <notifications@github.com>:

**Comment by patsoftware** [comment] 2015-08-13 16:02
I have did other research and in the themes\_styled directory of GA4 in dockbar.css file at row 755 i have found the ipotetic problem: 

@include respond-to(phone, tablet) { 
#navigation { 
display: none; 

&.open { 
display: block; 
} 
} 

The date of file is 16/04/2015 14:01. 
You have the same dockbar.css or other file? 

In GA2 version there isn't instruction about #navigation id. 
This is the difference about GA2 and GA4. 

Best regards 

Antonio Patarozzi

**Comment by marcoscv-work** [comment] 2015-08-15 01:30
Hi!

We can add this line anyway. Could you send me a pull request with the
line? In this way the people will be able to know your collaboration ;)

@include respond-to(phone, tablet) {
       #navigation {
             display: block;
       }
}

Thank you!

2015-08-13 18:02 GMT+02:00 patsoftware notifications@github.com:

**Comment by marcoscv-work** [comment] 2015-08-15 03:21
Resolved in last commit:

https://github.com/marcoscv-work/madrid-theme/commit/41272f07a5997845d9118277d0372f7887d78386

**Closed as completed** 2015-08-15 03:21 UTC

**Comment by patsoftware** [comment] 2015-08-17 07:40
I would like and i have tried but i cannot. 

How can i Do to put the reuest ? 

Best Regards 

Antonio Patarozzi

**Comment by marcoscv-work** [comment] 2015-08-17 10:39
I added the lines last Saturday, you can update your repository. It is
working correctly now.

Thank you!

2015-08-17 9:40 GMT+02:00 patsoftware notifications@github.com:
